# Generated by Django 3.2.4 on 2021-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classno', models.IntegerField()),
                ('slotno', models.IntegerField()),
                ('totstu', models.IntegerField()),
                ('allstu', models.IntegerField()),
                ('mindose', models.IntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
